In [2]:
# Scientific and vector computation for python
import numpy as np

# Plotting library
from matplotlib import pyplot


x = [[1., 0., 0.],
 [0., 1., 2.]]

np.ndim(x)

2

In [2]:
np.shape(x)

(2, 3)

In [3]:
np.size(x)

6

In [4]:
a = np.arange(15).reshape(3, 5)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
t = a[0, :]

In [25]:
theta=np.array([0.0, 0.0])
(theta.transpose() - 10)^2

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [11]:
a.shape

(3, 5)

In [14]:
a.ndim

2

In [40]:
a.dtype.name

'int64'

In [26]:
a.itemsize # size in bytes of each item

8

In [28]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((2, 3), dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
np.ones((3, 2)) - np.ones((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [42]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [49]:
np.arange(0, 2, 0.3) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [50]:
from numpy import pi
np.linspace(0, 2, 9) # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [61]:
x = np.linspace(0, 2 * pi, 5) # useful to evaluate function at lots of points
f = np.sin(x)

In [62]:
x

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [64]:
a = np.arange(6)   # 1d array
print(a)

[0 1 2 3 4 5]


In [65]:
b = np.arange(12).reshape(4, 3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [67]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [77]:
# to print the everything
# np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported
print(np.arange(10000)) #If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners

[   0    1    2 ... 9997 9998 9999]


In [80]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [81]:
# reset print options to default
np.set_printoptions(edgeitems=3, infstr='inf',linewidth=75, nanstr='nan', precision=8,suppress=False, threshold=1000, formatter=None)

In [82]:
#Arithmetic operations

In [83]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [85]:
c = a - b
c

array([20, 29, 38, 47])

In [86]:
b**2

array([0, 1, 4, 9])

In [87]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [88]:
a < 35

array([ True,  True, False, False])

In [4]:
A = np.array([[1, 1],[0,1]])

In [93]:
B = np.array([[2, 0],
              [3, 4]])

In [94]:
A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [95]:
A @ B     # matrix product

array([[5, 4],
       [3, 4]])

In [96]:
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

In [98]:
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [101]:
b += a
b

array([[9.51182162, 9.9504637 , 9.14415961],
       [9.94864945, 9.31183145, 9.42332645]])

In [103]:
a = rg.random((2, 3))
a

array([[0.32973172, 0.7884287 , 0.30319483],
       [0.45349789, 0.1340417 , 0.40311299]])

In [104]:
a.sum()

2.412007822394087

In [105]:
a.min()

0.13404169724716475

In [106]:
a.max()

0.7884287034284043

In [110]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
b.cumsum(axis=1)  # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [5]:
B = np.arange(3)
B

array([0, 1, 2])

In [114]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [115]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [6]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

In [7]:
ac = np.array([[2, 6], [3,4]])
ac

array([[2, 6],
       [3, 4]])

In [4]:
ac[0]

2

In [5]:
ac[1]

6

In [17]:
ac[:, 0]

array([2, 3])

In [18]:
ac[:]

array([[2, 6],
       [3, 4]])

In [11]:
np.zeros(2)

array([0., 0.])